language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t FrancisLin8993/TimeRetrievalAWS -f Dockerfile.dev .

script:
  - docker run FrancisLin8993/TimeRetrievalAWS npm run test -- --coverage
