language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t francislin8993/time-retrieval-aws -f Dockerfile.dev .

script:
  - docker run francislin8993/time-retrieval-aws npm run test -- --coverage
